all: clean build run
	 $(shell cd $(BIN); ls)
	python scrape_myfave.py

clean: # remove data and binary folder

build: # compile to binary (if you use interpreter, then do not implement it)

run: # run your binary